"""
A simple script to dynamically add source files to the project.

Author: Surge
Date: 2024-12-27
"""

import os

# The root directory of the project
ROOT_DIR = os.path.join(os.path.dirname(__file__), "..")

# The source directory of the project
SRC_DIR = os.path.join(ROOT_DIR, "src")

def find_sources():
    print("Scanning sources...")
    sources = []
    for root, _, files in os.walk(SRC_DIR):
        for file in files:
            if file.endswith(".cpp") or file.endswith(".c"):
                sources.append(os.path.relpath(os.path.join(root, file), ROOT_DIR))
    print("Found {} source files".format(len(sources)))
    return sources

def main():
    sources = find_sources()
    with open(os.path.join(os.path.dirname(__file__), "sources.cmake"), "w") as f:
        f.write("# AUTOGENERATED FILE\n#Run python3 ./scripts/scanSources.py to regenerate\n\nset(SOURCES")
        for source in sources:
            f.write(" " + source)
        f.write(")\n")

    print("Wrote scripts/sources.cmake")

if __name__ == "__main__":
    main()