# AUTOGENERATED FILE
#Run python3 ./scripts/scanSources.py to regenerate

set(SOURCES src/mesh.cpp src/phosphor.cpp src/texture.cpp src/window.cpp src/camera.cpp src/shader.cpp src/renderer/opengl_renderer.cpp src/renderer/vulkan_renderer.cpp)
